### ISSUE TITLE
Problems with set_string in fmu4cpp 

### ISSUE THREAD

**Issue by Now-Hyeok** [Ecos-platform/fmu4cpp#15]
hi 

I think need to modify the code in set_strings.

![image](https://github.com/Ecos-platform/fmu4cpp/assets/84857521/e1e58031-0257-4373-b1ce-68966ae0eaab)

booleans_  --> strings_ 

This will concatenate the input and output values of the string as normal.

**Comment by markaren** [comment]
Indeed, this is a bug. Thank you, will look at it soon.

**Comment by markaren** [comment]
Resolved in 454db6529bd5bba48a78741f4d14be72b749b36d
