### ISSUE TITLE
Errors attempting to Run Generated FMU through FMPy

### ISSUE THREAD

**Issue by Number-One-Intern** [Ecos-platform/fmu4cpp#16]
Hello, so after now figuring out how to run FMUs through FMI4cpp. I now would like to create and export an FMU from C++ code. However, whereas I generally understand how FMU's work. and how to read their .xml files. I still lack technical knowledge to construct them correctly. Which is why I am currently trying to create a simple FMU that has one input and output. The goal is to make an FMU that iterates the input variable by one each dostep and then outputs that value. However, I am having issues when I try to run the generated FMU through FMPY to test it. 

![image](https://github.com/user-attachments/assets/d49d7ce4-1ebc-43ba-8d22-c24497b3712d)

I am unsure what these errors mean. For reference here is the code I wrote by modifying the base file as told to do so in the README.md.
```
//
// FMU4cpp Hello World example -> Modified to attempt to create a counter variable and output it.
//

#include <fmu4cpp/fmu_base.hpp>
#include <utility>


using namespace fmu4cpp;

class Model : public fmu_base {

public:
    Model(const std::string &instanceName, const std::string &resources)
        : fmu_base(instanceName, resources) {

        register_variable(
                integer(
                        "counterIn", [this] { return counter_; }, [this](int value) { counter_ = value; })
                        .setCausality(causality_t::INPUT)
                        .setVariability(variability_t::DISCRETE));

        register_variable(
                integer(
                        "counterOut", [this] { return counter_; })
                        .setCausality(causality_t::OUTPUT)
                        .setVariability(variability_t::DISCRETE)
                        .setDependencies({get_int_variable("counterIn")->index()}));
        Model::reset();
    }

    bool do_step(double currentTime, double dt) override {
        //debugLog(fmi2OK, "hello@ " + std::to_string(currentTime));
        counter_++;
        return true;
    }

    void reset() override {
        counter_ = 0;
    }

private:
    int counter_;
};

model_info fmu4cpp::get_model_info() {
    model_info info;
    info.modelName = "TestCounter";
    info.description = "Create a simple FMU that inputs an integer variable, then iterates it by adding 1 each time the FMU advances state.";
    info.modelIdentifier = FMU4CPP_MODEL_IDENTIFIER;
    return info;
}

std::unique_ptr<fmu_base> fmu4cpp::createInstance(const std::string &instanceName, const std::string &fmuResourceLocation) {
    return std::make_unique<Model>(instanceName, fmuResourceLocation);
}
```
Then the CMakeLists.txt.
```
add_library(${modelIdentifier} SHARED
        model.cpp
        "$<TARGET_OBJECTS:fmu4cpp>")
target_include_directories(${modelIdentifier} PRIVATE ${PROJECT_SOURCE_DIR}/export/include)
target_compile_definitions(${modelIdentifier} PRIVATE FMU4CPP_MODEL_IDENTIFIER="${modelIdentifier}")

set(outputDir "$<1:${CMAKE_BINARY_DIR}/binaries/${TARGET_PLATFORM}>")

if (WIN32)
    set_target_properties(${modelIdentifier}
            PROPERTIES
            RUNTIME_OUTPUT_DIRECTORY "${outputDir}"
            )
else ()
    set_target_properties(${modelIdentifier}
            PROPERTIES
            PREFIX ""
            LIBRARY_OUTPUT_DIRECTORY "${outputDir}"
            )
endif ()

# Generate modelDescription.xml
add_custom_command(TARGET ${modelIdentifier} POST_BUILD
        WORKING_DIRECTORY "${CMAKE_BINARY_DIR}"
        COMMAND descriptionGenerator "${outputDir}/$<TARGET_FILE_NAME:${modelIdentifier}>")

function(generateFMU name)
    add_custom_command(TARGET ${modelIdentifier} POST_BUILD
            WORKING_DIRECTORY "${CMAKE_BINARY_DIR}"
            COMMAND ${CMAKE_COMMAND} -E tar "c" "${name}.fmu" --format=zip
            "${CMAKE_BINARY_DIR}/binaries"
            "${CMAKE_BINARY_DIR}/modelDescription.xml")
endfunction()

# Generate FMU
generateFMU("${modelIdentifier}")

# Make a copy for testing purposes
generateFMU("model")
```
Note: The same errors occur even if I try to run the unmodified base code.

**Comment by markaren** [comment]
I don't know when I will be able to look at this, but I don't think fmi2Get/setFMUState is implemented. Newer versions of fmpy might be stricter on this.

Try to edit https://github.com/Ecos-platform/fmu4cpp/blob/master/export/src/fmu4cpp/fmi2.cpp and add missing FMI2 functions (just throw an error in the method body).

**Comment by Number-One-Intern** [comment]
I probably did this wrong but here is the result of my attempt to add an fmi2GetFMUstate method.
![Screenshot 2024-07-16 082251](https://github.com/user-attachments/assets/27fbc769-3cf9-4a97-ba3c-68f1b8b20a82)
![Screenshot 2024-07-16 082526](https://github.com/user-attachments/assets/c3af916b-5d9e-4efa-9d92-1eb4185890e8)

**Comment by markaren** [comment]
> I probably did this wrong but here is the result of my attempt to add an fmi2GetFMUstate method.

Yes, the declaration is not the same as defined somewhere in the FMI header.

> Although variables were clunky to handle since I declared them as integers. Kept getting segmentation faults.

I can't say why.

> What would be an easier way to handle them? Declare them as Reals then read as Integers?

You can't read/write different types. If you declare a Real, you need to read a Real etc.
